### ISSUE TITLE
Support EO extensions in the STAC spec JSON result 

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/RGD-ScrumBoard#16]
- We need it for supporting UConn work, they are going to tag assets which bands harmonized

**Comment by aashish24** [comment]
Ref: https://github.com/stac-extensions/eo

**Comment by aashish24** [comment]
I will ask @matt-bernstein to send us the sample dataset.

**Comment by matt-bernstein** [comment]
> I will ask @matt-bernstein to send us the sample dataset.

@aashish24 here is the table of band information we will be referencing: https://gitlab.kitware.com/smart/watch/-/blob/master/watch/utils/util_bands.py

We will attach these fields to the STAC catalogs created during TA-1, upload them to RGD, and then use them as inputs for resampling/chipping in TA-2. I can provide more details on this workflow in our meeting if you have questions about it.

There are code samples in that file to show how the AWS and IARPA T&E STAC catalogs handle `eo`, and how I created these dicts from the catalogs. If you have access to the right credentials, you should be able to reproduce them [minus the fields I filled in by hand] by rerunning the code samples.
```python
Example:
    >>> from pystac_client import Client
    >>> cat = Client.open('https://earth-search.aws.element84.com/v0')
    >>> search = cat.search(bbox=[-110, 39.5, -105, 40.5], max_items=1, collections=['sentinel-s2-l1c'])
    >>> i = list(search.items())[0]
    >>> # one image per band
    >>> bands = [v.to_dict()['eo:bands'][0] for k,v in i.assets.items() if k.startswith('B')]
    >>>
    >>> from watch.utils.util_bands import *
    >>> assert dicts_contain(SENTINEL2, bands)
```

You can also work with these as `pystac.Band` objects instead of raw dicts:

```python
Example:
    >>> from pystac.extensions.eo import Band
    >>> from watch.utils.util_bands import *
    >>> for band in ALL_BANDS:
    >>>     band.pop('gsd', None)  # pystac doesn't support this yet
    >>>     b = Band.create(**band)
```
I personally haven't yet found this useful, but you might if you're using `pystac` elsewhere.
