### ISSUE TITLE
Architect RGD based applications

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/RGD-ScrumBoard#17]

**Comment by banesullivan** [comment]
Following a discussion between @brianhelba, @AlmightyYakob, and myself, the architecture plan moving forward is as follows:

We will create new Django Apps (capital A) for ResonantGeoData:
- `django-rgd`: the core ResonantGeoData app for geospatial data management
- `django-rgd-imagery`: extension for geospatial imagery
- `django-rgd-fmv`: extension for Full Motion Video data
- `django-rgd-geometry`: extension for shapefiles and other vector geometry
- `django-rgd-3d`: extension for 3D data (point clouds, meshes, etc.)

Each of these will be pip-installable and be able to be turned on as an installed app in a Django Project individually. This separation has a direct mapping to the current submodules in `rgd/geodata/models/` and they will be independent of each other (though each of the extensions will depend on `django-rgd`)

This separation will greatly improve dependency management. For example, the `fmv` module pulls in Kwiver and the `3d` module pulls in VTK. If a Project or client only wants to manage raster imagery then those are some *heavy* dependencies being pulled in for no good reason along with a lot of database clutter from the extra tables for those other modules.

These new apps will live in the currently existing `ResonantGeoData` repository each with its own `setup.py`.

Then we will have a new repository (name to be decided, cc @aashish24 - we need to meet with you to finalize the name) for the Django Project which is deployed to www.resonantgeodata.com. Further, we will have another repository for the AWS deployment since it only needs the `django-rgd` and `django-rgd-imagery` apps installed. These repositories will have minimal code and simply be a place to configure the Project and it's deployment.

This will enable us to create new Girder 4 Projects for other efforts that quickly utilize RGD's features and build from them.

Overall, this shouldn't take too much effort as it's primarily re-organizing the code, adding new `setup.py` files, and new CI/CD pipelines. We will have to halt development on RGD during this period but I do not foresee that being an issue as we are at a really good place to do this right now.

## Potential Issues / Roadblocks

One issue I am realizing at this point is that we will have to rethink/rebuild our permissions models (which we might have to do anyways from the rather serious issue in https://github.com/ResonantGeoData/ResonantGeoData/issues/413) in order for us to manage permissions in the core `django-rgd` app without it being aware of the downstream apps (e.g. `django-rgd-imagery`) -- cc @mcovalt.

## Preliminary Work

There are a handful of things I would like to do before this redesign since we will be deleting all of the migrations:

- Remove the `ModifiableEntry` model in favor of `django-extensions`' `TimeStampedModel`: https://github.com/ResonantGeoData/ResonantGeoData/pull/303
- Rename models to have a more clear convention across RGD
- Rethink the raster models to simplify the `RasterEntry` vs. `RasterMetaEntry` situations (and other similar cases)

**Comment by banesullivan** [comment]
Checklist as I make progress:

- [ ] Wrap up, merge, and/or close all open pull requests in `ResonantGeoData` repo
- [ ] Split current `ResonantGeoData` repo into two repos sharing the same history (new `RD-OpenGeo` repo)
    - [ ] Start a new `dev` branch in `ResonantGeoData` repo such that the deployment on Heroku is stable during development
    - [ ] Move Project-level issues over to the new `RD-OpenGeo` repo
- [ ] Create new Apps for each of the geodata submodules
    - [ ] Clear out project/deployment code/etc from `ResonantGeoData` repo
    - [ ] Add a `setup.py` for each App
    - [ ] Split tests per app and remake the GitHub Actions to individually test each app
    - [ ] Handle permissions issues - create a new permissions interface in the core app -- @mcovalt 
    - [ ] Start Refactoring model relationships such that no relationship depends on an ETL routine
    - [ ] Rename models to have a clear convention
    - [ ] Remake the HTML templates such that they are more easily extensible across Apps
    - [ ] Resolve as many outstanding issues as possible
    - [ ] Refactor the Python client in such a way that it can connect to Projects with different combinations of the Apps installed.
    - [ ] Review, review, and review with the team
    - [ ] Reset migrations
- [ ] Publish Docker images on Docker Hub or GitHub - to more easily share docker images with all of the dependencies pre-installed for easier dev across projects (the 2nd part of https://github.com/ResonantGeoData/ResonantGeoData/issues/405)
- [ ] Make https://github.com/ResonantGeoData/ResonantGeoData/pull/334 into a Dev Config that we can use across projects
- [ ] Use the cookie-cutter to create a new Project for `RD-WATCH` and other internal projects
- [ ] Improve READMEs across repositories
- [ ] Add documentation on all the models across Apps and how to extend the core models for new domain-specific needs
- [ ] Merge all work the main branch in `ResonantGeoData` and tag version `0.2.0` of the Apps and Python client and publish each app to PyPI
- [ ] Deploy `RD-OpenGeo` to Heroku and run demo data commands
- [ ] Deploy `RD-WATCH` to AWS and populate with data sources

**Comment by banesullivan** [comment]
Something happened and I deleted the progress checklist for this list. Reposting:

- [x] Wrap up, merge, and/or close all open pull requests in `ResonantGeoData` repo
- [x] Tag a release
- [x] Split current `ResonantGeoData` repo into two repos sharing the same history (new `RD-OpenGeo` repo)
- [x] Start a new `dev` branch in `ResonantGeoData` repo such that the deployment on Heroku is stable during development
- [x] Move Project-level issues over to the new `RD-OpenGeo` repo
- [x] Clear out project/deployment code/etc from `ResonantGeoData` repo
- [x] Create new Apps for each of the geodata submodules
- [x] Initial reorganization into seperate apps
- [x] Add a `setup.py` for each App
- [x] Split tests per app
- [x] remake the GitHub Actions to individually test each app
- [ ] Handle permissions issues - create a new permissions interface in the core app -- @mcovalt
- [ ] Refactor model relationships such that no relationship depends on an ETL routine
- [ ] Rename models to have a clear convention
- [ ] Remake the HTML templates such that they are more easily extensible across Apps
- [ ] Resolve as many outstanding issues as possible
- [ ] Refactor the Python client in such a way that it can connect to Projects with different combinations of the Apps installed.
- [ ] Clear out app code from `RD-OpenGeo` repo - install apps and get Project up and running
- [ ] Publish Docker images on Docker Hub or GitHub - to more easily share docker images with all of the dependencies pre-installed for easier dev across projects (the 2nd part of https://github.com/ResonantGeoData/ResonantGeoData/issues/405)
- [ ] Make https://github.com/ResonantGeoData/ResonantGeoData/pull/334 into a Dev Config that we can use across projects
- [ ] Use the cookie-cutter to create a new Project for `RD-WATCH` and other internal projects
- [ ] Improve READMEs across repositories and apps
- [ ] Add documentation on all the models across Apps and how to extend the core models for new domain-specific needs
- [ ] Review, review, and review with the team
- [ ] Reset migrations
- [ ] Merge all work the main branch in `ResonantGeoData` and tag version `0.2.0` of the Apps and Python client and publish each app to PyPI
- [ ] Deploy `RD-OpenGeo` to Heroku and run demo data commands
- [ ] Deploy `RD-WATCH` to AWS and populate with data sources

**Comment by banesullivan** [comment]
This comment seems to keep getting deleted while editing. Reposting:

- [x] Wrap up, merge, and/or close all open pull requests in `ResonantGeoData` repo
- [x] Tag a release
- [x] Split current `ResonantGeoData` repo into two repos sharing the same history (new `RD-OpenGeo` repo)
- [x] Start a new `dev` branch in `ResonantGeoData` repo such that the deployment on Heroku is stable during development
- [x] Move Project-level issues over to the new `RD-OpenGeo` repo
- [x] Clear out project/deployment code/etc from `ResonantGeoData` repo
- [x] Create new Apps for each of the geodata submodules
- [x] Initial reorganization into seperate apps
- [x] Add a `setup.py` for each App
- [x] Split tests per app
- [x] remake the GitHub Actions to individually test each app
- [x] Handle permissions issues - create a new permissions interface in the core app
- [x] Handle redirect view for `spatial_entry/<pk>/` URLs
- [x] Refactor model relationships such that no relationship depends on an ETL routine
- [x] Rename models to have a clear convention
- [x] Remake the HTML templates such that they are more easily extensible across Apps
- [x] Resolve as many outstanding issues as possible
- [x] Clear out app code from `RD-OpenGeo` repo - install apps and get Project up and running
- [x] Review, review, and review with the team
- [x] Reset migrations
- [x] Merge all work the main branch in `ResonantGeoData` and tag version `0.2.0` of the Apps and Python client and publish each app to PyPI

Post-release of the apps:

- [x] Make https://github.com/ResonantGeoData/ResonantGeoData/pull/334 into a Dev Config that we can use across projects
- [x] Use the cookie-cutter to create a new Project for `RD-WATCH` and other internal projects
- [ ] Deploy `RD-OpenGeo` to Heroku and run demo data commands
- [x] Deploy `RD-WATCH` to AWS and populate with data sources
