### ISSUE TITLE
"Verify Your E-mail Address" hangs in AWS deployment

### ISSUE THREAD

**Issue by matt-bernstein** [ResonantGeoData/RGD-ScrumBoard#2]
Not sure if this should go here.

I have an account on the RGD instance at https://rgd.beamio.co/ that was created manually. When logging in for the first time, I hit that screen, but did not get an email after an hour. An admin verified my email manually and now I can use the web interface and python client as expected.

Added 'documentation' tag because I'm wondering if there's a doc in progress for AWS deployment? If so, this should be added to it.

**Comment by banesullivan** [comment]
This is resolved using the same email service as the Heroku deployment.

**Comment by banesullivan** [comment]
Apparently, this is still happening... looking into fixing

**Comment by banesullivan** [comment]
Actually, nope this IS working. The process is as follows (I will document elsewhere as appropriate too):

1. User signs up on the sign up page
2. They are hit with an account inactive error (this is because an admin has to approve their sign up)
3. An admin manually sets their account as active
4. The user tries to sign in again and they are hit with "Verify Your E-mail Address" message
5. The user receives the email and follows the link to log in
